/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef REALTIMEDATA_ACCESS_H
#define REALTIMEDATA_ACCESS_H

#include "../public/public.h"
#include "realTimeData_columns.h"


/** User-defined data access functions for data in table realTimeDataTable */
/** row level accessors */
Netsnmp_First_Data_Point realTimeDataTable_get_first_data_point;
Netsnmp_Next_Data_Point realTimeDataTable_get_next_data_point;
int             realTimeDataTable_commit_row(void **my_data_context,
                                             int new_or_del);
void           *realTimeDataTable_create_data_context(netsnmp_variable_list
                                                      * index_data,
                                                      int column);

/** column accessors */
long           *get_realTimeDataIndex(void *data_context, size_t *ret_len);
long           *get_realTimeDataX1(void *data_context, size_t *ret_len);
long           *get_realTimeDataY2(void *data_context, size_t *ret_len);

void init_table_realtime_data(void);


#endif                          /* REALTIMEDATA_ACCESS_H */
