/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef REALTIMEDATA_H
#define REALTIMEDATA_H

/** other required module components */
config_require(book-app-mib/realtimedata/realTimeData_access)
config_require(book-app-mib/realtimedata/realTimeData_checkfns)

    /*
     * function declarations 
     */
     void            init_realTimeData(void);
     void            initialize_table_realTimeDataTable(void);
     Netsnmp_Node_Handler realTimeDataTable_handler;

// 将realTimeDataZ部分的代码拷贝过来
void            init_realTimeDataZ(void);
FindVarMethod   var_realTimeDataZ;


/*
 * column number definitions for table realTimeDataTable 
 */
#include "realTimeData_columns.h"

/*
 * enum definions 
 */
#include "realTimeData_enums.h"

#endif /** REALTIMEDATA_H */
