/*
 * Note: this file originally auto-generated by mib2c using
 *        : $
 * 
 */
#ifndef REALTIMEDATA_CHECKFNS_H
#define REALTIMEDATA_CHECKFNS_H

/*
 * these functions are designed to check incoming values for 
 * columns in the realTimeDataTable table for legality with respect to 
 * datatype and value according to local conventions.  You should modify
 * them as appropriate.  They will be called from parent check_value
 * functions that are auto-generated using mib2c and the parent functions
 * should NOT be modified.
 */


#endif                          /* REALTIMEDATA_CHECKFNS_H */
