/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef REALTIMEDATA_COLUMNS_H
#define REALTIMEDATA_COLUMNS_H

/*
 * column number definitions for table realTimeDataTable 
 */
#define COLUMN_REALTIMEDATAINDEX		1
#define COLUMN_REALTIMEDATAX1		2
#define COLUMN_REALTIMEDATAY2		3
#endif                          /* REALTIMEDATA_COLUMNS_H */
