/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef NOTIFICATIONOBJS_H
#define NOTIFICATIONOBJS_H
config_require(book-app-mib/alarms/sysAlarms)
#include "../public/public.h"

/*
 * function declarations 
 */
void            init_notificationObjs(void);
FindVarMethod   var_notificationObjs;
WriteMethod     write_alarmCounter;

#endif                          /* NOTIFICATIONOBJS_H */
