/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "sysAlarms.h"

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;
//static oid      snmptrap_oid[] = { 1, 3, 6, 1, 6, 3, 1, 1, 4, 1, 0 };

static int
send_sysAlarmNotify_trap(void)
{
    netsnmp_variable_list *var_list = NULL;
    const oid       sysAlarmNotify_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 9999, 9999, 1, 3, 0, 1 };
    const oid       alarmCounter_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 9999, 9999, 1, 11, 3, 0 };
    const oid       alarm1_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 9999, 9999, 1, 11, 1, 0 };
    const oid       alarm2_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 9999, 9999, 1, 11, 2, 0 };

	static int alarmCounter;
	static int alarm1;
	static char alarm2[MAX_CHAR_LEN];

	// 获取数据准备发送
	snmp_get_data(SHM_ALARM,ALARM1,sizeof(int),&alarm1); 
	snmp_get_data(SHM_ALARM,ALARM2,sizeof(alarm2),alarm2); 
	snmp_get_data(SHM_ALARM,ALARM_COUNTER,sizeof(int),&alarmCounter);
    DEBUGMSGTL(("alarms", "PARAMETERB = %d,%s(%d),%d\n\n", alarm1,alarm2, strlen(alarm2),alarmCounter  ));
    /*
     * 设置 snmpTrapOid.0
     */
    snmp_varlist_add_variable(&var_list,
                              snmptrap_oid, snmptrap_oid_len,
                              ASN_OBJECT_ID,
                              sysAlarmNotify_oid,
                              sizeof(sysAlarmNotify_oid));

    /*
     * sysAlarmNotify的定义顺序添加变量绑定
     */
    snmp_varlist_add_variable(&var_list,
                              alarmCounter_oid,
                              OID_LENGTH(alarmCounter_oid), ASN_INTEGER,
                             (u_char *)&alarmCounter, sizeof(int));
    snmp_varlist_add_variable(&var_list,
                              alarm1_oid, OID_LENGTH(alarm1_oid),
                              ASN_INTEGER,
                             (u_char *)&alarm1, sizeof(int));
    snmp_varlist_add_variable(&var_list,
                              alarm2_oid, OID_LENGTH(alarm2_oid),
                              ASN_OCTET_STR,
                              (u_char *)alarm2, strlen(alarm2)+1);

    /*
     * 如果必要的话，可以加入其他需要上送的OID
     */

    send_v2trap(var_list);// 发送trap
    snmp_free_varbind(var_list); // 清空变量

    return SNMP_ERR_NOERROR;
}


/***********************************************************
* Description:如果 counter 大于0则发送告警，否则不发送
***********************************************************/
static void judege_send_alarms(int counter)
{

	#define SEND_TRAP_PERIOD    (5)  
	static unsigned int trap_clientreg = 0;

	if( counter > 0)
	{
		if( trap_clientreg	== 0)
		{
			 send_sysAlarmNotify_trap();
			 // 注册每5秒周期性的发送TRAP
			 trap_clientreg = 
			  snmp_alarm_register(SEND_TRAP_PERIOD, 
			      SA_REPEAT, send_sysAlarmNotify_trap, NULL);  
				   
		}
	}else
	{
		if( trap_clientreg != 0 )
		{
			snmp_alarm_unregister(trap_clientreg);
			trap_clientreg = 0;
		}		
	}
}

/***********************************************************
* Description:系统初始化时注册，
每秒周期获取告警标志 alarmCounter
如果其值大于0则发送告警
***********************************************************/
static void  
read_alarmdata_repeat(unsigned int clientreg, void *clientarg)
{
	int alarmCounter = 0 ; // 实时获取的值

	snmp_get_data(SHM_ALARM,ALARM_COUNTER,sizeof(int),&alarmCounter);
	DEBUGMSGTL(("alarms", "alarmCounter =%d\n",alarmCounter ));
	judege_send_alarms( alarmCounter ); // 判断发送告警

	return;	
}

/***********************************************************
* Description:系统初始化时注册接口
***********************************************************/
void register_read_alarmdata()
{
#define READ_PERIOD (1)

	static unsigned int trap_clientreg = 0;
	trap_clientreg = 
	   snmp_alarm_register(READ_PERIOD, 
			      SA_REPEAT, read_alarmdata_repeat, NULL);
	return;

}

