/*
 * Note: this file originally auto-generated by mib2c using
 * mib2c.old-api-refactor.conf Sat Oct 11 17:57:43 2014
 * zhangchunqiang 2014-10 $
 */
#ifndef PARAMETER_H
#define PARAMETER_H

/* !!! please fill the module path completely that we have developed !!!*/
#include "../public/public.h"

/*--define scalar magic number,easy enum*/
typedef enum
{
   PARAMETERA = 1,
   PARAMETERB,
}E_scalar_parameter_magic;

/*--define table magic number*/
typedef enum
{
     PARAMETERINDEX = 1,
     PARAMETERC1, 
}E_table_parameter_magic;


/* function declarations */
  void init_parameter(void);
  FindVarMethod var_parameter;
  FindVarMethod var_parameterTable;

/*one scalar write is ok*/
  WriteMethod write_parameter_scalar;


/* --table write */
  WriteMethod write_parameterTable;

/*if you have other special code,you can write here */

#endif /* PARAMETER_H */
