/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef PARAMETER_H
#define PARAMETER_H
#include "../public/public.h"

/*
 * function declarations 
 */
void            init_parameter(void);
FindVarMethod   var_parameter;
FindVarMethod   var_parameterTable;
WriteMethod     write_parameterA;
WriteMethod     write_parameterB;
WriteMethod     write_parameterC1;

#endif                          /* PARAMETER_H */
