/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef SYSALARMS_H
#define SYSALARMS_H
#include "../public/public.h"

/*
 * function declarations 
 */
//int             send_sysAlarmNotify_trap(void);
void register_read_alarmdata();


#endif                          /* SYSALARMS_H */
